#!/bin/sh
### BEGIN INIT INFO
# Provides:          myapp
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start myapp at boot time
# Description:       Enable service provided by myapp.
### END INIT INFO

case "\$1" in
    start)
        echo "Starting myapp..."
        # Start v4l2-ctl command
        /usr/bin/v4l2-ctl --set-fmt-video=width=2016,height=1520,pixelformat=GB10 --stream-mmap -d /dev/video4 &
        # Start python scripts
        /usr/bin/python3 /home/root/sjxsocket_server.py &
        /usr/bin/python3 /home/root/sjxsend_uart_linux.py &
        ;;
    stop)
        echo "Stopping myapp..."
        # Add commands to stop the processes if necessary
        # Example: pkill -f socket_server.py
        # Example: pkill -f send_uart_linux.py
        ;;
    restart)
        \$0 stop
        \$0 start
        ;;
    *)
        echo "Usage: \$0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0